apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mywebserver
  name: mywebserver
spec:
  containers:
  - image: nginx
    name: mywebserver
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
